<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "sob_grup_18";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
               
                /* TOPIC */
                "INSERT INTO " + schema + ".TOPIC VALUES(NEXT VALUE FOR TOPIC_GEN,'Accio')",
                "INSERT INTO " + schema + ".TOPIC VALUES(NEXT VALUE FOR TOPIC_GEN, 'Aventura')",
                "INSERT INTO " + schema + ".TOPIC VALUES(NEXT VALUE FOR TOPIC_GEN, 'Rol')",
                "INSERT INTO " + schema + ".TOPIC VALUES(NEXT VALUE FOR TOPIC_GEN, 'Simulació')",
                "INSERT INTO " + schema + ".TOPIC VALUES(NEXT VALUE FOR TOPIC_GEN, 'Casual')",
                
                /* CONSOLA */
                
                "INSERT INTO " + schema + ".CONSOLA VALUES(NEXT VALUE FOR CONSOLA_GEN,'Nintendo')",
                "INSERT INTO " + schema + ".CONSOLA VALUES(NEXT VALUE FOR CONSOLA_GEN, 'Play')",
                "INSERT INTO " + schema + ".CONSOLA VALUES(NEXT VALUE FOR CONSOLA_GEN, 'PC')",
                "INSERT INTO " + schema + ".CONSOLA VALUES(NEXT VALUE FOR CONSOLA_GEN, 'Xbox')",
                "INSERT INTO " + schema + ".CONSOLA VALUES(NEXT VALUE FOR CONSOLA_GEN, 'Wii')",
                
                /* USUARI */
                
                "INSERT INTO " + schema + ".USUARI (id, nomUsuari, contrasenya) VALUES(NEXT VALUE FOR USUARI_GEN, 'Pol', 'poletinho54')",
                "INSERT INTO " + schema + ".USUARI (id, nomUsuari, contrasenya) VALUES(NEXT VALUE FOR USUARI_GEN, '123321', 'Dounia')",
                "INSERT INTO " + schema + ".USUARI (id, nomUsuari, contrasenya) VALUES(NEXT VALUE FOR USUARI_GEN, 'sob', 'sob')",
                
                 /* JOC */
                
                "INSERT INTO " + schema + ".JOC (id, nom, preu, disponibilitat, descripcio, adress, consola_id, topic_id) VALUES (NEXT VALUE FOR JOC_GEN, 'MarioBros', 25.99, 1, 'Fontanero Corriendo', 'ALTAFULLA', 1, 3)",
                "INSERT INTO " + schema + ".JOC (id, nom, preu, disponibilitat, descripcio, adress, consola_id, topic_id) VALUES (NEXT VALUE FOR JOC_GEN ,'HungerGames', 20.99, 1, 'Tengo hambre', 'CANONJA',3, 2)",
                "INSERT INTO " + schema + ".JOC (id, nom, preu, disponibilitat, descripcio, adress, consola_id, topic_id) VALUES (NEXT VALUE FOR JOC_GEN,'MarioCart', 19.99, 1, 'Coches', 'REUS', 2, 1)",
                "INSERT INTO " + schema + ".JOC (id, nom, preu, disponibilitat, descripcio, adress, consola_id, topic_id) VALUES (NEXT VALUE FOR JOC_GEN,'JustDance', 14.99, 1, 'Bailando', 'TARRAGONA', 5, 4)",
                "INSERT INTO " + schema + ".JOC (id, nom, preu, disponibilitat, descripcio, adress, consola_id, topic_id) VALUES (NEXT VALUE FOR JOC_GEN,'FIFA24', 29.99, 1, 'Furbo', 'BUENOS AIRES', 2 , 5)",
                "INSERT INTO " + schema + ".JOC (id, nom, preu, disponibilitat, descripcio, adress, consola_id, topic_id) VALUES (NEXT VALUE FOR JOC_GEN,'NBA2K24', 29.99, 1, 'Basquet', 'TOKYO', 4 , 5)",
                "INSERT INTO " + schema + ".JOC (id, nom, preu, disponibilitat, descripcio, adress, consola_id, topic_id) VALUES (NEXT VALUE FOR JOC_GEN,'CallOfDuty', 19.99, 1, 'Disparos', 'ESPANYA', 2 , 5)",
                "INSERT INTO " + schema + ".JOC (id, nom, preu, disponibilitat, descripcio, adress, consola_id, topic_id) VALUES (NEXT VALUE FOR JOC_GEN,'Pokemon', 9.99, 1, 'Animales', 'CHINA', 1 , 2)",
                
                /* LLOGUERS */
                
                "INSERT INTO " + schema + ".LLOGUER VALUES (NEXT VALUE FOR LLOGUER_GEN,15,'2024-02-09', 1)",
                "INSERT INTO " + schema + ".LLOGUER VALUES (NEXT VALUE FOR LLOGUER_GEN,26.9,'2024-01-04', 2)",
             
                
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
